from Media import Media

class Documentary(Media):
    def __init__(self):
        super().__init__()
        self.production_year = ...
        # self.season = ...

    # def showinfo(self):
    #     ...

    # def download(self):
    #     ...
