class Media:
    def __init__(self,name,director,IMDB_cvore,duration):
        self.name = name
        self.director = director
        self.IMDB_cvore = IMDB_cvore
        self.url = duration
        self.duration = ...
        self.casts = ...
        self.genre = ...
        self.country = ...

    def showinfo(self):
        ...

    def download(self):
        ...
