from Media import Media

class Series(Media):
    def __init__(self,name,director,IMDB_cvore,duration):
        super().__init__(name,director,IMDB_cvore,duration)
        self.number_episodes = ...
        self.number_season = ...
        self.start_year = ...
        self.end_year = ...
        self.Finished = ...

    # def showinfo(self):
    #     ...

    # def download(self):
    #     ...
